## Step1. 데이터를 정렬한다

In [6]:
import pandas as pd

In [5]:
## 최소값, 최대값 산출

In [2]:
## 최고값, 최대값 각각의 개수를 산출 
## 최대값개수 = initList.count(최대값)

In [3]:
## 평균계산 : 초기리스트합 - (최소값 * 최소값개수) - (최대값 * 최대값개수)

In [7]:
priceList = [100,200,150,170]
priceTuple = (100,200,150,170)
priceSet = set(priceList)
priceSet

In [20]:
priceset1 = {100,150,200,170}
priceset2 = {100,139,210,170}

In [22]:
priceset1.difference(priceset2)

{150, 200}

In [23]:
# 2020년도 1주차 ~ 6주차까지 데이터가 다 있는지를 확인해야 한다.

In [26]:
existWeek = {202001, 202002, 202003, 202005, 202006}
allweek = {202001,202002,202003,202004,202005,202006}

allweek = existWeek.difference(allweek)
allweek

set()

In [48]:
yearweekList = [202001,202002,202003,202004]
priceList = [10,20,30,40]

priceDict = {"price": priceList ,
            "yearweek": yearweekList}
## 대괄호를 사용하면서, 오류가 났을때  리스트=대괄호 / 다른 데이터 타입에 특징을 생각하기.

In [29]:
pd.DataFrame(priceList)

0
0  10
1  20
2  30
3  40

In [40]:
pd.DataFrame(priceDict)

price  yearweek
0     10    202001
1     20    202002
2     30    202003
3     40    202004

In [50]:
dic = {"name":"sec","id":"300000","address":"suwon"}
print(dic)

{'name': 'sec', 'id': '300000', 'address': 'suwon'}


In [51]:
print(dic['name'])

sec


In [53]:
dic["name"] = "sec2"
dic["stock"] = "yes"
print(dic)
print(dic["stock"])

{'name': 'sec2', 'id': '300000', 'address': 'suwon', 'stock': 'yes'}
yes


In [56]:
dic.pop("name")
print(dic)

{'id': '300000', 'address': 'suwon', 'stock': 'yes'}


In [57]:
tuple1 = ("미국","LEDTV","01")
tuple2 = ("미국","LEDTV","02")

In [59]:
dic = {tuple1: 2.5,
      tuple2: 1.2}

In [60]:
dic[tuple1]

2.5

In [64]:
## dic 정의
dic = {"name":"sec","id":"300000","address":"suwon"}

## pop을 사용하여 “id”:”300000” 삭제
dic.pop("id")
print(dic)

{'name': 'sec', 'address': 'suwon'}


In [66]:
pd.read_csv("../dataset/customerdata.csv")

CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000    3            6    1.679181  Big-Screen-lover
1    A14219  3642.441950    2            4    2.682023      Sleeping-dog
2    A15312  3653.884565    2            5    3.208202      Sleeping-dog
3    A16605  3713.211107    2            6    0.900000        Early-bird
4    B10634  3391.074215    2            4    2.453656      Sleeping-dog
..      ...          ...  ...          ...         ...               ...
145  Z13253  3678.800000    2            5    2.463670  Big-Screen-lover
146  Z13534  3662.437527    3            6    0.900000        Early-bird
147  Z16428  3516.500000    2            5    2.371301  Big-Screen-lover
148  Z16735  3300.100000    2            5    1.704942  Big-Screen-lover
149  Z19835  3326.526183    2            6    1.200000        Early-bird

[150 rows x 6 columns]

In [1]:
import pandas as pd

In [2]:
productId = ["LEDTV", "LEDTV", "LEDTV", "LEDTV"]
yearweek = [202101, 202102, 202103, 202104]
volValue = [100, 120, 130, 140]
pd.DataFrame(productId, columns = ["product"],)


product
0   LEDTV
1   LEDTV
2   LEDTV
3   LEDTV

In [8]:
producdic = {"product":productId}
pd.DataFrame(producdic)

product
0   LEDTV
1   LEDTV
2   LEDTV
3   LEDTV

In [81]:
productIddict = {"productdict" : productId,
                "yearweekdict": yearweek,
                "volValuedict": volValue}
pd.DataFrame(productIddict)

productdict  yearweekdict  volValuedict
0       LEDTV        202101           100
1       LEDTV        202102           120
2       LEDTV        202103           130
3       LEDTV        202104           140

In [85]:
import numpy as np

In [87]:
np.linspace(start=1, stop=100, num=20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [90]:
!pip show numpy 

Name: numpy
Version: 1.18.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\smart-14\anaconda3\lib\site-packages
Requires: 
Required-by: tables, statsmodels, seaborn, scipy, scikit-learn, PyWavelets, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, h5py, Bottleneck, bokeh, bkcharts, astropy


In [109]:
np.random.randint(low=0,high=10,)

5

In [101]:
np.random.rand()

array([0.33870909])

In [103]:
np.random.random(10)

array([0.81408858, 0.39279659, 0.7598488 , 0.84852392, 0.87459336,
       0.84645374, 0.95231462, 0.34365275, 0.34946794, 0.42807225])

In [106]:
np.random.randn()

1.1544829656178994

In [112]:
np.random.random_integers(0, 11 + 1)

<ipython-input-112-5cc03954abaa>:1: DeprecationWarning: This function is deprecated. Please call randint(0, 12 + 1) instead
  np.random.random_integers(0, 11 + 1)


12

In [116]:
val1 = np.random.randint(0,10)
val1

8

In [117]:
import numpy as np

In [122]:
num = !pip list
pd.DataFrame(num)

0
0           Package                            Version
1    ---------------------------------- -----------...
2            -umpy                              1.18.5
3            alabaster                          0.7.12
4             anaconda-client                    1.7.2
..                                                 ...
236          yapf                               0.30.0
237           zict                               2.0.0
238           zipp                               3.1.0
239             zope.event                         4.4
240           zope.interface                     4.7.1

[241 rows x 1 columns]

In [8]:
import pandas as pd

In [9]:
date = ['16.02.29', '16.02.26', '16.02.25', '16.02.24', '16.02.23']
date2 = ['17.02.29', '17.02.26', '17.02.25', '17.02.24', '17.02.23']
qty = ["100", "101", "102", "103", "104"]
         
pd.DataFrame(date, columns=['date'])

date
0  16.02.29
1  16.02.26
2  16.02.25
3  16.02.24
4  16.02.23

In [27]:
## 각 정보를 정의한다.
value = ['초등학교', '중학교', '고등학교', '대학교', '직업']
firstYear = ['200103','200703','201003','201303','202103']
lastYear = ['200702', '201002', '201302', '201902', '202112']
where = ['광진구','광진구','중랑구','서대문구','강서구']

## 데이터 프레임을 정의한다.
personaldict = {'value': value,
                'firstYear': firstYear,
                'lastyear': lastYear,
                'where': where }
dataFrame = pd.DataFrame(personaldict)

## 데이터 프레임을 출력한다.
print(dataFrame)

    value   firstYear lastyear     where
0      초등학교    200103   200702       광진구
1       중학교    200703   201002       광진구
2      고등학교    201003   201302       중랑구
3       대학교    201303   201902      서대문구
4        직업    202103   202112       강서구


In [12]:
# df1 = pd.DataFrame(value, columns=["구분"])
# df2 = pd.DataFrame(value, columns=["입학년도"])
# df3 = pd.DataFrame(value, columns=["졸업년도"])
# df4 = pd.DataFrame(value, columns=["위치"])

구분
0  초등학교
1   중학교
2  고등학교
3   대학교
4    직업

In [1]:
## 데이터 프레임을 생성한다.
dataFrame = pd.DataFrame(personaldict)

NameError: name 'pd' is not defined

In [16]:
## 각 정보를 정의한다.
value = ['초등학교', '중학교', '고등학교', '대학교', '직업']
firstYear = ['200103','200703','201003','201303','202103']
lastYear = ['200702', '201002', '201302', '201902', '202112']
where = ['광진구','광진구','중랑구','서대문구','강서구']

## 데이터 프레임을 정의한다.
personaldict = {'value': value,
                'firstYear': firstYear,
                'lastyear': lastYear,
                'where': where }
pd.DataFrame( zip(value,firstYear, lastYear, where),
            columns='학교)

SyntaxError: positional argument follows keyword argument (<ipython-input-16-7ed866cb3968>, line 13)